# Generated by Django 4.0.4 on 2022-08-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='body',
        ),
    ]
