# Generated by Django 4.0.4 on 2022-08-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_posts_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='title',
            new_name='task',
        ),
    ]
