# Generated by Django 4.0.4 on 2022-08-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='work',
        ),
    ]
